export const NOTES_LIST_REQUEST = 'NOTES_LIST_REQUEST';
export const NOTES_LIST_SUCCESS = 'NOTES_LIST_SUCCESS';
export const NOTES_LIST_FAILURE = 'NOTES_LIST_FAILURE';

export const NOTES_CREATE_REQUEST = 'NOTES_CREATE_REQUEST';
export const NOTES_CREATE_SUCCESS = 'NOTES_CREATE_SUCCESS';
export const NOTES_CREATE_FAILURE = 'NOTES_CREATE_FAILURE';

export const NOTES_UPDATE_REQUEST = 'NOTES_UPDATE_REQUEST';
export const NOTES_UPDATE_SUCCESS = 'NOTES_UPDATE_SUCCESS';
export const NOTES_UPDATE_FAILURE = 'NOTES_UPDATE_FAILURE';

export const NOTES_DELETE_REQUEST = 'NOTES_DELETE_REQUEST';
export const NOTES_DELETE_SUCCESS = 'NOTES_DELETE_SUCCESS';
export const NOTES_DELETE_FAILURE = 'NOTES_DELETE_FAILURE';