export const NOTES_LIST_REQUEST = 'NOTES_LIST_REQUEST';
export const NOTES_LIST_SUCCESS = 'NOTES_LIST_SUCCESS';
export const NOTES_LIST_FAILURE = 'NOTES_LIST_FAILURE';

export const NOTES_CREATE_REQUEST = 'NOTES_CREATE_REQUEST';
export const NOTES_CREATE_SUCCESS = 'NOTES_CREATE_SUCCESS';
export const NOTES_CREATE_FAILURE = 'NOTES_CREATE_FAILURE';